create table tb_agendamentos (id int8 generated by default as identity, data date, dia_agenda dia, horario time, material varchar(255), primary key (id));
create table tb_emprestimos (id int8 generated by default as identity, data date, horario time, material varchar(255), primary key (id));
create table tb_materiais (id int8 generated by default as identity, descricao varchar(255), titulo varchar(255), primary key (id));
create table tb_projetos (id int8 generated by default as identity, coordenador varchar(255), descricao varchar(255), integrante varchar(255), material varchar(255), titulo varchar(255), primary key (id));
