
    create table tb_agendamento (
       id int8 generated by default as identity,
        data date,
        dia_agenda int4,
        horario time,
        material varchar(255),
        id_projeto int8,
        primary key (id)
    );

    create table tb_emprestimo (
       id int8 generated by default as identity,
        data date,
        horario time,
        id_material int8,
        id_projeto int8,
        primary key (id)
    );

    create table tb_material (
       id int8 generated by default as identity,
        descricao TEXT,
        titulo TEXT,
        primary key (id)
    );

    create table tb_projeto (
       id int8 generated by default as identity,
        coordenador TEXT,
        descricao TEXT,
        integrante TEXT,
        material TEXT,
        titulo TEXT,
        primary key (id)
    );

    alter table if exists tb_agendamento 
       add constraint FKht4ix6brft9lsnx825fs75tgi 
       foreign key (id_projeto) 
       references tb_projeto;

    alter table if exists tb_emprestimo 
       add constraint FKowrnny78bcp4xx72n20fvtrie 
       foreign key (id_material) 
       references tb_material;

    alter table if exists tb_emprestimo 
       add constraint FKfo7dp7my29kke5yu6j2hvw0bq 
       foreign key (id_projeto) 
       references tb_projeto;
